/* PURGE */
DROP TABLE IF EXISTS verifications;
DROP TABLE IF EXISTS user_reports;
DROP TABLE IF EXISTS station_reports;
DROP TABLE IF EXISTS comment_reports;
DROP TABLE IF EXISTS post_reports;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS comment_votes;
DROP TABLE IF EXISTS post_votes;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS subposts;
DROP TABLE IF EXISTS subcomments;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS crewmates;
DROP TABLE IF EXISTS captains;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS stations;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS admins;

DROP FUNCTION IF EXISTS comment_id;
DROP SEQUENCE IF EXISTS comment_id_seq;
DROP FUNCTION IF EXISTS post_id;
DROP SEQUENCE IF EXISTS post_id_seq;

DROP TYPE IF EXISTS report_status_enum;
DROP TYPE IF EXISTS gender_enum;

DROP FUNCTION IF EXISTS stringify_bigint;
DROP FUNCTION IF EXISTS pseudo_encrypt;